version: '3'

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:10-1
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
#   elasticsearch:
#     build:
#       context: elasticsearch/
#       args:
#         ELK_VERSION: $ELK_VERSION
#     volumes:
#       - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     environment:
#       ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#     networks:
#       - elk


#   api:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#       args:
#         DATABASE_CLIENT: mongo
#         DATABASE_HOST: ds135796.mlab.com
#         DATABASE_PORT: 35796
#         DATABASE_SRV: 'false'
#         DATABASE_NAME: cscpharmaen
#         DATABASE_USERNAME: cscpharma
#         DATABASE_PASSWORD: fuckoff11
#         DATABASE_SSL: 'false'
#         DATABASE_AUTHENTICATION_DATABASE: cscpharmaen

#     command: npm run start
#     ports:
#       - 1337:1337

#     restart: always



# networks:

#   elk:
#     driver: bridge
